plugins {
	id 'multiloader-common'
}

configurations {
	commonJava {
		canBeResolved = true
	}
	commonResources {
		canBeResolved = true
	}
}

dependencies {
	compileOnly project(':common')

	commonJava project(path: ':common', configuration: 'commonJava')
	commonResources project(path: ':common', configuration: 'commonResources')
}

tasks.named('compileJava', JavaCompile) {
	dependsOn(configurations.commonJava)
	source(configurations.commonJava)
}

processResources {
	dependsOn(configurations.commonResources)
	from(configurations.commonResources)
}

tasks.named('build') {
	finalizedBy('outputRemapJar')
}

def vsMappingsFile = file("${project.rootDir}/mappings/vs.tiny")

tasks.register('remapVSinJar', JavaExec) {
	dependsOn 'remapJar'

	def jarFile = tasks.named('remapJar').get().archiveFile.get().asFile
	ext.outputFile = jarFile

	classpath = configurations.remapTool
	mainClass = "net.fabricmc.tinyremapper.Main"
	standardOutput = new FileOutputStream("${buildDir}/tiny-remapper.log")
	args = [
		jarFile,
		ext.outputFile,
		vsMappingsFile,
		'named',
		'shadow',
	]
}

tasks.register('outputRemapJar') {
	dependsOn 'remapVSinJar'
	doLast {
		def jarFile = tasks.named('remapVSinJar').get().ext.outputFile
		def targetDir = file("${rootDir}/mod-output/")
		copy {
			from jarFile
			into targetDir
		}
	}
}

tasks.named('javadoc', Javadoc).configure {
	dependsOn(configurations.commonJava)
	source(configurations.commonJava)
}

tasks.named('sourcesJar', Jar) {
	dependsOn(configurations.commonJava)
	from(configurations.commonJava)
	dependsOn(configurations.commonResources)
	from(configurations.commonResources)
}
