name: Tag Publish

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: publish-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: false

  test:
    name: Check & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: microsoft
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Check
        run: ./gradlew check --no-daemon

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: microsoft
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Build
        run: ./gradlew build --no-daemon
      - name: Upload Build Artifacts
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: mod-output/*.jar
          overwrite: true
          if-no-files-found: error

  upload_release_assets:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    needs:
      - create_release
      - test
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-assets
          path: ./release-assets
      - name: Upload Release Assets
        uses: zyxkad/upload-release-asset-dir@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_dir: ./release-assets

  publish_maven:
    name: Publish Maven
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout Source
        uses: actions/checkout@v5
        with:
          path: ./source
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-root-directory: ./source
      - name: Checkout Maven
        uses: actions/checkout@v5
        with:
          repository: LiterMC/maven
          ref: maven
          path: ./maven
      - name: Publish To Maven
        env:
          local_maven_url: file://${{ github.workspace }}/maven
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          WORKDIR=$(pwd)
          for i in {1..3}; do
            cd "${WORKDIR}/source"
            ./gradlew publishMavenJavaPublicationToMavenRepository
            cd "${WORKDIR}/maven"
            git add .
            git commit -m 'publish: ${{ github.repository }} ${{ github.ref_name }}' || exit $?
            git push origin HEAD:maven && exit 0

            echo "::error::"
            echo "::error::Push failed, tried $i"
            echo "::error::"

            git fetch origin maven
            git reset --hard origin/maven
          done
          exit 1
